export {default as ProtectedRoute} from '../Route/ProtectedRoute'
export {default as ProtectedUserRoute} from '../Route/ProtectedUserRoute'
export {default as Admin} from './Dashboards/Admin'
export {default as User} from './Dashboards/User'
export {default as UserPage} from './Users/UserPage'
export {default as Login} from './Login'
export {default as Logout} from './Logout'
export {default as DisassembleByCateegoriy} from './Exams/DisassembleByCateegoriy'
export {default as ExamsTable} from './Exams/ExamsTable'
export {default as Repositore} from './Repositore/Repositore'
export {default as Candidates} from './Candidates/Candidates'
export {default as CreateUser} from './Users/Actions/CreateUser' 
export {default as TabelCandidates} from './Candidates/TabelCandidates'
export {default as PageExam} from './Candidates/ExamPage'
export {default as DiagramDishboard } from './Diagram/DiagramDishboard'
